name: Manual2 workflow

on:
  workflow_dispatch:
    inputs:
      name:
        description: Name
        type: string
        default: test

      age:
        description: Age
        type: number
        required: true

      gender:
       description: Gender
       type: choice
       options:
         - male
         - female

jobs:
  manual:
    runs-on: ubuntu-latest

    steps:
      - name: Name
        run: echo "${{ inputs.name }}"

      - name: Age
        run: echo "${{ inputs.age }}"
      - name:  Gender
        run: echo "${{ inputs.gender }}"










                        
